# Generated by Django 3.2.9 on 2021-11-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('SeatNo', models.AutoField(primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=100)),
                ('ReleaseDate', models.DateField()),
                ('AttendeeFirstName', models.CharField(max_length=100)),
                ('AttendeeSecondName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=50)),
                ('ReleaseDate', models.DateField()),
            ],
        ),
    ]
