# Generated by Django 3.2.9 on 2021-11-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='ReleaseDate',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='ReleaseDate',
        ),
        migrations.AlterField(
            model_name='movies',
            name='MovieName',
            field=models.CharField(max_length=150),
        ),
    ]
